sudo: required
services:
  - docker

before_install:
  - docker build -t jleshardin/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jleshardin/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "testreact"
  env: "Testreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-193482107952"
  bucket_path: "testreact"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"